# Generated by Django 3.1.7 on 2021-05-21 15:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210322_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='anons',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=270, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Статья'),
        ),
    ]
