# Generated by Django 3.1.7 on 2021-05-12 10:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=150, verbose_name='Тема вопроса')),
                ('full_text', models.TextField(verbose_name='Блок с вопросом')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата создания вопроса')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Информационный блок  из форума',
                'verbose_name_plural': 'Информационные блоки из форума',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('full_answer', models.TextField(verbose_name='Блок с ответом')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата создания ответа')),
                ('forum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forum.forum')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ответ на вопрос из форума',
                'verbose_name_plural': 'Ответы на вопросы из форума',
            },
        ),
    ]
