# Generated by Django 3.1.7 on 2021-03-22 09:chihuahua

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('anons', models.CharField(max_length=270, verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Информационный блок')),
            ],
            options={
                'verbose_name': 'Информационный блок про породу собаки',
                'verbose_name_plural': 'Информационные блоки про породы собак',
            },
        ),
    ]
