# Generated by Django 3.1.7 on 2021-04-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210408_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockinfo',
            name='full_text',
        ),
        migrations.RemoveField(
            model_name='blockinfo',
            name='image',
        ),
        migrations.AddField(
            model_name='blockinfo',
            name='age',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Продолжительность жизни'),
        ),
        migrations.AddField(
            model_name='blockinfo',
            name='characteristic',
            field=models.TextField(blank=True, null=True, verbose_name='Характеристики породы'),
        ),
        migrations.AddField(
            model_name='blockinfo',
            name='height',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Рост'),
        ),
        migrations.AddField(
            model_name='blockinfo',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='История происхождения породы собаки'),
        ),
        migrations.AddField(
            model_name='blockinfo',
            name='pet_care',
            field=models.TextField(blank=True, null=True, verbose_name='Уход за питомцем'),
        ),
        migrations.AddField(
            model_name='blockinfo',
            name='weight',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Вес'),
        ),
    ]
