# Generated by Django 3.1.7 on 2021-05-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210429_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main', verbose_name='Изображение'),
        ),
    ]
