# Generated by Django 3.1.7 on 2021-05-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210513_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='media/profile_avatar/emptyAvatar.jpg', upload_to='profile_avatar', verbose_name='Аватар пользователя'),
        ),
    ]
