# Generated by Django 3.1.7 on 2021-05-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20210518_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='../profile_avatar/emptyAvatar.jpg', null=True, upload_to='profile_avatar', verbose_name='Аватар пользователя'),
        ),
    ]
