# Generated by Django 3.1.7 on 2021-04-20 10:13

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название видео')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, verbose_name='Видео')),
                ('date', models.DateTimeField(verbose_name='Дата добавления видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
