# Generated by Django 3.1.7 on 2021-04-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название видео'),
        ),
    ]
